### ISSUE TITLE
PARAMOUNT-V2-YTDLP: Input URLs not including all Episodes

### ISSUE THREAD

**Issue by BeeMuffins** [ohmybahgosh/YT-DLP-SCRIPTS#1]
Hello.  First thank you for taking the time to develop and share these scrips.

I've noticed that for shows where there are multiple seasons, with more than one season having greater than 18 episodes, it seems that the generation of the ```input_urls``` is incomplete. From my testing, it seems that the ```input_urls``` does not capture anything after episode 18 for any of the seasons.  

Below are two examples where I've noticed this.  I've also attached the ```input_urls``` file that was created.
https://www.paramountplus.com/shows/blue_bloods/
https://www.paramountplus.com/shows/hawaii_five_0/

[blue_bloods_INPUT_URLS.txt](https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/files/6995577/blue_bloods_INPUT_URLS.txt)
[hawaii_five_0_INPUT_URLS.txt](https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/files/6995578/hawaii_five_0_INPUT_URLS.txt)

I did not realize I was missing these until referencing back to thetvdb.com and noticing some seasons had more episodes then I was seeing in the text file.  This is also because I noticed that depending on how you select the individual season and 'show more' button from the paramount website it may also only show up to 18 episodes for certain seaons despite there being more if you went directly to that season page and then selected 'show more'. 

Let me know if any other information would be helpful.

**Comment by ohmybahgosh** [comment]
I'll dig in first thing tomorrow morning and figure out a workaround!

**Comment by ohmybahgosh** [comment]
Just fixed it, please try with the latest commit I just pushed!

**Comment by BeeMuffins** [comment]
That fixed it.  Thanks for looking into and  updating it so quickly.  I should have though to at least search the code for the #18 🤦 

Again appreciate all the scripts you've shared.

**Comment by ohmybahgosh** [comment]
No problem!  If you have any custom requests for other sites, feel free to open an issue and I'll see what I can put together!
