### ISSUE TITLE
Add Checks to Re-Download Corrupt/Incorrect Episode Files For P+

### ISSUE THREAD

**Issue by DreadMcLaren** [ohmybahgosh/YT-DLP-SCRIPTS#13]
Add checks to detect corrupt/incorrect episode files that are downloaded and attempt a re-download. Because P+ is known for looping audio/freezing video, this feature would be nice.

**Comment by ohmybahgosh** [comment]
I'll add some checks tomorrow

**Comment by DreadMcLaren** [comment]
Thank you!

**Comment by DreadMcLaren** [comment]
Any progress on this?

**Comment by tomck** [comment]
Most likely editing the script to add --hls-prefer-native may resolve it.

ytdl-org/youtube-dl#27972

**Comment by ohmybahgosh** [comment]
My apologies everyone, I just had a lil baby boy a couple months ago and I'm just now getting my brain enough sleep to dive back in to these!

**Comment by jschwalbe** [comment]
Also curious about something like this. :)
