### ISSUE TITLE
What can i edit to make this work in Canada?

### ISSUE THREAD

**Issue by PrSinister** [ohmybahgosh/YT-DLP-SCRIPTS#14]
The URLs all have /ca/ after the discoveryplus.com. It finds both seasons of this show:

https://www.discoveryplus.com/ca/show/90-day-the-single-life-discovery-originals-ca

But doesn't find any episodes.

So far, i have modified:

x-disco-client to `WEB:UNKNOWN:dplus_us:1.25.0`
x-disco-params to `realm=go,siteLookupKey=dplus_ca,bid=dplus,hn=www.discoveryplus.com,hth=ca,features=ar`
x-accept-language to `en-CA,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,en-GB;q=0.6,en-US;q=0.5`
and i have modified https://www.discoveryplus.com/video/#g to `https://www.discoveryplus.com/ca/video/#g`

But it still finds 2 seasons and 0 episodes.

I have a feeling the culprit is this line:

`curl -s "https://us1-prod-direct.discoveryplus.com/cms/collections/89438300356657080631189351362572714453?include=default&decorators=viewingHistory,isFavorite,playbackAllowed&pf\[seasonNumber\]=${SEASON_NUMBER}&pf\[show.id\]=${SHOW_ID}" \`

I don't know where to get that collections number... All i could find that resembles this URL in the headers is:

`https://us1-prod-direct.discoveryplus.com/cms/routes/show/90-day-the-single-life-discovery-originals-ca?include=default&decorators=viewingHistory,isFavorite,playbackAllowed`

I have tried changing that number to an other ID i found in one of the responses and i get the exact same result so i that is why i think the collections URL is the problem. 

How can i get that URL from my Chrome Dev Tools?

**Comment by PrSinister** [comment]
Changed the curl to hardcode the routes url above and it worked. Problem now is yt-dlp doesn't support the Canadian URLs.

Still need the proper generic curl url though

**Comment by arth6250** [comment]
Same issue here, is the "routes/show" vs "collections" the main issue in the curl?
