### ISSUE TITLE
OUTPUTDIR folder name needs two digits

### ISSUE THREAD

**Issue by b33z** [ohmybahgosh/YT-DLP-SCRIPTS#15]
Not really sure how to say this in your proper terms, but here goes...

First, the Discovery Plus script works like a dream! Loving it, Thanks!

One thing that kinda "bugs" me tho, is the output folder for the season uses only one digit instead of two. 

Example:
x:\TvShow1\Season 1\
vs
x:\TvShow2\Season 01\
(screenshot attached)
![sshot-1](https://user-images.githubusercontent.com/5906583/152704325-65480bea-3753-490f-aaaa-b740192e028c.png)

Not really a big deal at all and certainly not a bug, just an annoyance since shows that have more that 10 seasons will be listed in the wrong order in some programs like for example Windows Explorer.

Thanks again for your time and efforts!!! And sorry if I did this wrong...
-B

**Comment by ohmybahgosh** [comment]
> You should be able to do that by editing this line from the discovery script
> 
> https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/blob/2b039ba1762a2a85cc26789bfb7a9d793dd34e47/DISCOVERY-PLUS-YTDLP/DISCOVERY_PLUS-YTDLP#L242
> 
> Change it to: -o '%(series)s/Season %(season_number)**02d**/%(series)s - S%(season_number)02dE%(episode_number)02d: %(title)s.%(ext)s' \

If you'd like the credit, go ahead and submit a PR and I'll commit it!  If not, I can go ahead and modify/test your line above
