### ISSUE TITLE
download single season?

### ISSUE THREAD

**Issue by b33z** [ohmybahgosh/YT-DLP-SCRIPTS#16]
Love this script! 
Would be great if one could dl just one single season (or even episode) rather than the whole series.

think i might have to learn some bash so i can contribute some of these things myself! lol

thanks again OMBG!

**Comment by ohmybahgosh** [comment]
Totally doable!  I've neglected these scripts the past couples months, non-stop preparing for our first child 😀

Let me see what I can do, should have something by Monday/Tuesday!

**Comment by DrMxrcy** [comment]
I would love to see this as well if you are still maintaining these!

**Comment by ohmybahgosh** [comment]
My apologies everyone, I just had a lil baby boy a couple months ago and I'm just now getting my brain enough sleep to dive back in to these!

**Comment by DrMxrcy** [comment]
Great thanks and congrats @ohmybahgosh

**Comment by ohmybahgosh** [comment]
## Wrote the basic functions on my phone last night, I'll clean em up and format it to match the script.. Then it'll go live!



![Screenshot_20220702-102532](https://user-images.githubusercontent.com/77786782/177004853-4d733df2-f441-47c7-a21d-1c6c094ba02e.png)
