### ISSUE TITLE
MTV-YTDLP: Usage on other sites (nickjr), subtitles, & metadata

### ISSUE THREAD

**Issue by BeeMuffins** [ohmybahgosh/YT-DLP-SCRIPTS#2]
**Nickjr**
This script also works at http://www.nickjr.com However, given that episodes at nickjr tend to be multi-episodes in one, I ran into a issue with the current script when it creates directories as nickjr uses ```/``` in the file name a lot to separate the episodes.

I made the following modification, though not sure it's the most efficient:
https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/blob/fc24e0d6f7b8498ba51312bf11829dc9ad3077eb/MTV-YTDLP/MTV-YTDLP#L56

```EPISODE_TITLE=$(cat MTV_JSON/MTV.json | jq -r --slurp 'first(.[].playlist_title)' | sed -e 's/\// - /g')```

**Subtitles & Metadata**
It's commented out, but I was using a similar command to what you have here to get subtitles and metadata. 
https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/blob/fc24e0d6f7b8498ba51312bf11829dc9ad3077eb/MTV-YTDLP/MTV-YTDLP#L63

Doing this I had issues with getting ```ffmpeg``` to bring in that information.  I was able to find a solution for subtitles, but have not had any luck with keeping metadata yet, not sure if you know a way for that. I updated the below which works for the subtitles:
https://github.com/ohmybahgosh/YT-DLP-SCRIPTS/blob/fc24e0d6f7b8498ba51312bf11829dc9ad3077eb/MTV-YTDLP/MTV-YTDLP#L73 ```ffmpeg -f concat -i inputs.txt -c copy -scodec copy "${FINAL_MERGED_FILENAME}"```

**Other**
You mentioned it on the other issue, but if you wanted to look into a script to pull all the episodes from nickjr for a series that would be amazing.  There show list as an example http://www.nickjr.com/paw-patrol/ contains a lot of videos and not all of them are episodes.  The episodes seem to have a tag on them as Full Episode or contain that in the URL.

I wasn't sure how you wanted to handle the changes whether updating on MTV-YTDLP, creating a separate site specific script, just having my notes in the event it helps someone else, etc., so I did not PR.

**Comment by ohmybahgosh** [comment]
Greatly appreciate getting feedback on these scripts!

I'll dig in tomorrow morning, as I've been meaning to fix filename issues for both this script and the paramount script.  I'm gonna build in some more checks as well, that'll identify the examples you posted.

As for the NickJr, I'll make it as it's own script, as my next project is to merge all these scripts in to one central menu driven script :)

**Comment by BeeMuffins** [comment]
Great stuff.  I like really like the idea of a menu driven script, so many different possibilities with that.

**Comment by ohmybahgosh** [comment]
So I spent some time yesterday scraping some stuff for work, and while writing a loop I realized I didn't try xidel on the MTV script.. MTV's site has all the metadata in the html source code.. So I'll map those out to variables, and then I should be able to push those metadata variables in to the final merged episode file...I'll get something pushed out later today!

**Comment by ohmybahgosh** [comment]
This is on the top of my to-do list!  I have the xpaths scripted via xidel to grab the metadata, just gotta clean up the formatting a bit so that ffmpeg can embed the metadata to the final output!

**Comment by ohmybahgosh** [comment]
Feel free to re-open this if this is still active
