### ISSUE TITLE
Parallel error - Unraid

### ISSUE THREAD

**Issue by iamthesq** [ohmybahgosh/YT-DLP-SCRIPTS#21]
Getting an error when running on Unraid

<img width="849" alt="Pasted_Image_10_18_22__12_27_AM" src="https://user-images.githubusercontent.com/23680652/196343431-fbf8d1ef-3622-4d58-8e7f-16087e639ee6.png">

**Comment by joe-eklund** [comment]
Hey I am still getting this error on Ubuntu 22.04. I see you recently closed this, but I just cloned the repo so have the most up to date code.

Any ideas @ohmybahgosh ? The only difference is now it says `line 251`.
