### ISSUE TITLE
DISCOVERY-PLUS-YTDLP: "jq_util_inputs_next_input_cb" failed

### ISSUE THREAD

**Issue by kalmaguer98** [ohmybahgosh/YT-DLP-SCRIPTS#23]
I downloaded JQ win64 .exe from here: https://github.com/stedolan/jq/releases/tag/jq-1.6 and put it in my cygwin64 path just like I did for aria2. I also installed all the cygwin jq packages just in case (along with sed).

After inputting the show URL and cookies, I get this for selecting seasons:

![jq_util_inputs_next_input_cb failed](https://user-images.githubusercontent.com/55248039/198037231-fd01e70e-0715-42a4-adc6-c3e54c80b2b3.png)

Then 0 episodes show up:

![0 episodes found](https://user-images.githubusercontent.com/55248039/198038846-ab6c241c-727f-4594-bcdf-0d959b977a31.png)

Not sure if something was changed with discovery where the script is broken or I'm doing something wrong, but the input URLs come up empty. Any help is appreciated!

**Comment by ohmybahgosh** [comment]
Fixed in both scripts
