### ISSUE TITLE
Discovery plus unable to find episode URLS.

### ISSUE THREAD

**Issue by MatthewC1314** [ohmybahgosh/YT-DLP-SCRIPTS#24]
So I have tried with both versions of the discovery plus scripts as-well as with several different show, but each time I try to get the episodes the script return"0 episodes found". It is able to tell me the exact count of all seasons but can't find any episode urls. I have used this script for a while without issue, I reinstalled Sed and Jq to no avail. Here is one of the links I tried to download.
https://www.discoveryplus.com/show/dirty-jobs
Any help is greatly appreciated.

**Comment by Shadeslayermasta** [comment]
Having the same issue, I was wondering if it was because I am taking a cookie file from brave with get cookies.txt and running this on Ubuntu WSL. How are you generating the cookies file and is it from outside the OS?

**Comment by MatthewC1314** [comment]
I've tried the cookies with getcookies.txt and editThisCookie. I think this is a problem with JQ, but I lack the programming knowledge to figure it out.

**Comment by ohmybahgosh** [comment]
I'll dig in to this today

**Comment by JasonMeudt** [comment]
> I'll dig in to this today

Any news on this?

**Comment by MatthewC1314** [comment]
Any luck with this?

**Comment by dwchx** [comment]
Still broken

**Comment by DukeChocula** [comment]
Yup. Broken for me as well.

A time consuming alternative is to get a browser extension like Link Gopher, go to each season. Pick "Extract Links by Filter", and filter by "video" which will grab all the links. Save those in a text file (I prefer to do 1 text file for each season)

Then do 

yt-dlp --cookies /wherever/your/cookies.txt --external-downloader aria2c -a /media/season1/episodes.txt

Not nearly as elegant but works for the time being.

**Comment by MatthewC1314** [comment]
I was able to fix it. It is a bit juvenile but it works. I have posted it in this pastebin.

https://pastebin.com/qUXQnbxn

**Comment by dean142** [comment]
> 

Thanks for that fix, mine hasn't been working since November

**Comment by ohmybahgosh** [comment]
Fixed in both scripts, please re-open if this didn't fix it...basically they modified their JSON a bit, so just had to update SED to remove some new prefixes
