### ISSUE TITLE
Request for watch.foodnetwork.com

### ISSUE THREAD

**Issue by am133** [ohmybahgosh/YT-DLP-SCRIPTS#4]
Would very much appreciate if it would be possible to get the addition of a script for https://watch.foodnetwork.com

Seems to be very similar to discovery so hopefully wouldn't be a lot of additional work to implement. Thanks!

**Comment by ohmybahgosh** [comment]
Apologies, this may be stale, but not forgotten!  Work has been crazy as of late, but it's on my to-do list!

**Comment by ohmybahgosh** [comment]
Feel free to re-open this if this is still active
