### ISSUE TITLE
files showing up as 8.3 versions

### ISSUE THREAD

**Issue by jleiss** [ohmybahgosh/YT-DLP-SCRIPTS#6]
I run the script on a debian 10 box and did a dump of Halloween baking championship, but then when I connect to the folder via samba and look at the files via directory opus the files are showing up in  8.3 file name format.

![Untitled](https://user-images.githubusercontent.com/2677329/134546039-820da3f2-7da4-40fb-a94c-8f234b8d6ea9.jpg)

**Comment by ohmybahgosh** [comment]
I'm not 100% sure what _8.3 format_ exactly means, sadly!

Could you try vieiwing the files via a SSH/SFTP connection?

**Comment by jleiss** [comment]
https://www.computerhope.com/jargon/num/8-3-format.htm

weirdly enough it does show up fine connecting to the machine via sftp through filezilla.

**Comment by ohmybahgosh** [comment]
Hmm, maybe it's an encoding issue via the program you use to connect with?

Try to see if there are any settings you can adjust via the samba client :)

**Comment by jleiss** [comment]
I'll check,  never seen it before though and I work in linux and windows all the time. Do you think it wqould be able to pull live content like this https://www.fox.com/skip-and-shannon-undisputed/ would save me alot of time cleaning up commercials after recording it from IPTV.

**Comment by jleiss** [comment]
adding more to this, so I can see them in long format with SSH, but I am not able to transfer them.. As it is not able to access them via long name.

![image](https://user-images.githubusercontent.com/2677329/134692806-501a077b-4b6d-4c77-8096-0ffde667e8de.png)

**Comment by jleiss** [comment]
I was able to fix the 8.3 issue by adjusting your template output and making it more unix friendly.

here is the adjusted output template:

      -o "%(series)s/Season_%(season_number)s/%(series)s_S%(season_number)02dE%(episode_number)02d_%(title)s.%(ext)s" \

example output attached

![image](https://user-images.githubusercontent.com/2677329/134726601-b4cbf5ea-476e-4f72-a88b-bb8d3479b1cb.png)

**Comment by ohmybahgosh** [comment]
Strange, but I glad you were able to fix it!  I also run Debian 10 on a couple servers, and haven't ran in to this issue, but if you ran in to it I'm sure someone else might!  Thanks for your solution :)

**Comment by jleiss** [comment]
you're welcome. I think it has to do with the spacing in the name as linux doesn't care for it very much.
